# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='VerificationCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
