# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170822_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='EMail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
