# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalJourney',
            fields=[
                ('PersonalJourneyID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonalJourneyName', models.CharField(max_length=50)),
                ('PersonalJourneyContent', models.TextField()),
                ('Points', models.TextField()),
                ('Status', models.CharField(max_length=1)),
                ('IsOpen', models.CharField(max_length=1)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('CreateDate', models.DateTimeField()),
                ('ModifyDate', models.DateTimeField()),
                ('CreateUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonalJourney_CreateUser', to='users.UserAccount')),
                ('ModifyUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonalJourney_ModifyUser', to='users.UserAccount')),
            ],
        ),
    ]
