# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('personalJourneys', '0002_remove_personaljourney_modifyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalJourneyComment',
            fields=[
                ('PersonalJourneyCommentID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('CreateDate', models.DateTimeField()),
                ('CreateUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonalJourneyComment_CreateUser', to='users.UserAccount')),
                ('PersonalJourney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonalJourneyComment_personalJourney', to='personalJourneys.PersonalJourney')),
            ],
        ),
    ]
