# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalJourneys', '0003_personaljourneycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalJourneyDetail',
            fields=[
                ('PersonalJourneyDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Latitude', models.CharField(max_length=30)),
                ('Longitude', models.CharField(max_length=30)),
                ('CreateDate', models.DateTimeField()),
                ('PersonalJourney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonalJourneyDetail_personalJourney', to='personalJourneys.PersonalJourney')),
            ],
        ),
    ]
