# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('ChatID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('CreateDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('UserID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('UserPicture', models.CharField(default='', max_length=300)),
                ('EMail', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('LastPassword', models.CharField(max_length=50)),
                ('LastLoginTime', models.DateTimeField()),
                ('IsEnabled', models.CharField(max_length=1)),
                ('IsVerification', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('UserFriendID', models.AutoField(primary_key=True, serialize=False)),
                ('CreateDate', models.DateTimeField()),
                ('CreateUser', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='UserFriend_CreateUser', to='users.UserAccount')),
                ('FriendUser', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='UserFriend_FriendUser', to='users.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='CreateUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Chat_CreateUser', to='users.UserAccount'),
        ),
        migrations.AddField(
            model_name='chat',
            name='FriendUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Chat_FriendUser', to='users.UserAccount'),
        ),
    ]
