# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('GroupChatID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.CharField(blank=True, max_length=50)),
                ('CreateDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('GroupRoleID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('GroupRoleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ROAGroup',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=50)),
                ('GroupPicture', models.CharField(blank=True, max_length=100)),
                ('CreateDate', models.DateTimeField()),
                ('ModifyDate', models.DateTimeField()),
                ('CreateUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ROAGroup_CreateUser', to='users.UserAccount')),
                ('ModifyUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ROAGroup_ModifyUser', to='users.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('UserInGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserInGroup_Group', to='groups.ROAGroup')),
                ('GroupRole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserInGroup_GroupRole', to='groups.GroupRole')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserInGroup_User', to='users.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='groupchat',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GroupChat_Group', to='groups.ROAGroup'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GroupChat_User', to='users.UserAccount'),
        ),
    ]
