# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=50)),
                ('GroupPicture', models.CharField(blank=True, max_length=100)),
                ('CreateDate', models.DateTimeField()),
                ('ModifyDate', models.DateTimeField()),
                ('CreateUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group_CreateUser', to='users.UserAccount')),
                ('ModifyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group_ModifyUser', to='users.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('GroupRoleID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('GroupRoleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('UserInGroup', models.AutoField(primary_key=True, serialize=False)),
                ('Group', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='groups.Group')),
                ('GroupRole', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='groups.GroupRole')),
                ('User', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='users.UserAccount')),
            ],
        ),
    ]
